name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=7.21.0
  - notebook=6.2.0
  - jupyterlab=3.0.10
  - cookiecutter=2.1.1
  - hydra-core=1.0.6
  - matplotlib=3.3.4
  - pandas=1.5.3
  - git=2.39.2
  - pip=23.0.1
  - pip:
      - mlflow==2.0.1
      - wandb==0.13.10
